/*
 * generated by Xtext 2.36.0
 */
package tdt4250.matrixgame.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMatrixGameScopeProvider extends DelegatingScopeProvider {
}
