/*
 * generated by Xtext 2.36.0
 */
package tdt4250.matrixgame.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MatrixGameAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("tdt4250/matrixgame/parser/antlr/internal/InternalMatrixGame.tokens");
	}
}
