/*
 * generated by Xtext 2.36.0
 */
package tdt4250.matrixgame.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tdt4250.matrixgame.parser.antlr.internal.InternalMatrixGameParser;
import tdt4250.matrixgame.services.MatrixGameGrammarAccess;

public class MatrixGameParser extends AbstractAntlrParser {

	@Inject
	private MatrixGameGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMatrixGameParser createParser(XtextTokenStream stream) {
		return new InternalMatrixGameParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GameLogic";
	}

	public MatrixGameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MatrixGameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
