/*
 * generated by Xtext 2.36.0
 */
package tdt4250.matrixgame;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MatrixGameStandaloneSetup extends MatrixGameStandaloneSetupGenerated {

	public static void doSetup() {
		new MatrixGameStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
