/*
 * generated by Xtext 2.36.0
 */
package tdt4250.matrixgame;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MatrixGameRuntimeModule extends AbstractMatrixGameRuntimeModule {
}
