/*
 * generated by Xtext 2.36.0
 */
package tdt4250.matrixgame.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tdt4250.matrixgame.xtext.ui.internal.XtextActivator;

public class MatrixGameUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("tdt4250.matrixgame.MatrixGame");
	}

}
