<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="game" nsURI="http://www.ntnu.no/tdt4250/MatrixGame" nsPrefix="game">
  <eClassifiers xsi:type="ecore:EClass" name="Tile">
    <eOperations name="interact">
      <eParameters name="action" eType="#//Action"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tilePlace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tileType" lowerBound="1"
        eType="#//TileType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAccessible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xCoordinate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yCoordinate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eOperations name="performAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionType" eType="#//ActionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eOperations name="getCurrentStatus" eType="#//Tile"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="turnsTaken" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flagsPlaced" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tile" lowerBound="1" eType="#//Tile"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eOperations name="takeAction" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="takes_action" upperBound="-1"
        eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionType">
    <eLiterals name="NONE"/>
    <eLiterals name="REVEAL"/>
    <eLiterals name="MOVE"/>
    <eLiterals name="TOGGLE"/>
    <eLiterals name="ATTACK"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TileType">
    <eLiterals name="BASIC"/>
    <eLiterals name="REWARD"/>
    <eLiterals name="OBSTACLE"/>
    <eLiterals name="INTERACTIVE"/>
    <eLiterals name="CRASH" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mapSizeMustBeSquare mapSizeMustFitScreen tileSizeMustBeSquare"/>
    </eAnnotations>
    <eOperations name="initializeMap"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tile" lowerBound="4" upperBound="-1"
        eType="#//Tile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amountOfTiles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapSizeX" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapSizeY" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameLogic">
    <eOperations name="applyAction" eType="#//State">
      <eParameters name="action" eType="#//Action"/>
      <eParameters name="tile" eType="#//Tile"/>
    </eOperations>
    <eOperations name="isGameOver"/>
    <eOperations name="generateStartingPosition" eType="#//Tile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        upperBound="2" eType="#//Player" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="map" lowerBound="1" eType="#//Map"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions_played" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has_state" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gameName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
