<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="game" nsURI="http://www.ntnu.no/tdt4250/MatrixGame" nsPrefix="game">
  <eClassifiers xsi:type="ecore:EClass" name="GameLogic">
    <eOperations name="switchPlayer"/>
    <eOperations name="isGameOver"/>
    <eOperations name="checkWin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="makeMove">
      <eParameters name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eParameters name="col" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gameName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="playerX" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="playerO" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grid" lowerBound="1" eType="#//Grid"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPlayer" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar" changeable="false"
        defaultValueLiteral="playerX"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="character" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cells" lowerBound="1" upperBound="-1"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//Cell"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" lowerBound="3" upperBound="-1"
        eType="#//Cell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Grid">
    <eOperations name="getCell" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar">
      <eParameters name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eParameters name="col" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eOperations>
    <eOperations name="setCell">
      <eParameters name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eParameters name="col" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eParameters name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    </eOperations>
    <eOperations name="isFull" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" lowerBound="3" upperBound="-1"
        eType="#//Row" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="map" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game" abstract="true"/>
</ecore:EPackage>
