/*
 * generated by Xtext 2.36.0
 */
package tdt4250.matrixgame.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MatrixGameUiModule extends AbstractMatrixGameUiModule {

	public MatrixGameUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
